
package com.zenika.user.soapservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-07-08T11:55:37.789+02:00
 * Generated source version: 3.0.1
 */

@WebFault(name = "getUserException", targetNamespace = "http://www.services.zenika.com/user")
public class GetUserException extends Exception {
    
    private java.lang.String getUserException;

    public GetUserException() {
        super();
    }
    
    public GetUserException(String message) {
        super(message);
    }
    
    public GetUserException(String message, Throwable cause) {
        super(message, cause);
    }

    public GetUserException(String message, java.lang.String getUserException) {
        super(message);
        this.getUserException = getUserException;
    }

    public GetUserException(String message, java.lang.String getUserException, Throwable cause) {
        super(message, cause);
        this.getUserException = getUserException;
    }

    public java.lang.String getFaultInfo() {
        return this.getUserException;
    }
}
