package com.zenika.user.soapservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-07-08T11:55:37.862+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://www.services.zenika.com/user", name = "userEndpoint")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UserEndpoint {

    @WebMethod
    @WebResult(name = "getUserResponse", targetNamespace = "http://www.services.zenika.com/user", partName = "getUserOut")
    GetUserResponse getUser(
            @WebParam(partName = "getUserIn", name = "getUserRequest", targetNamespace = "http://www.services.zenika.com/user")
            GetUserRequest getUserIn
    ) throws GetUserException;

    @WebMethod
    @WebResult(name = "getAllUsersResponse", targetNamespace = "http://www.services.zenika.com/user", partName = "getAllUsersOut")
    GetAllUsersResponse getAllUsers(
            @WebParam(partName = "getAllUsersIn", name = "getAllUsersRequest", targetNamespace = "http://www.services.zenika.com/user")
            GetAllUsersRequest getAllUsersIn
    );
}
